title : LookSee
tagline: ...crazy cool tagline...
author :
  name : Kevin Harvey
  email : kevharvey at gmail com
  github : kevharvey
  twitter : kev_harv
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
